### PR TITLE
publish subwasm crates

### PR DESCRIPTION
**Pull request by btwiuse**
Hi, I have transferred the ownership of the subwasm crate and its dependencies to you on crates.io. Feel free to remove me after you accept the ownership.

Last year I have made some necessary changes to the Cargo.toml manifest in each crate in order for them to be successfully published, but forgot to open a pull request and transfer crate ownership. 

I'm sorry for the inconvenience this may cause. Now I have rebased those changes onto master branch.

In addition to that, I believe these lines need to be changed to a existing version on crates.io before you run `cargo publish`
```
$ git grep 'git = "https://github.com' | grep Cargo.toml
lib/Cargo.toml:sp-version = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/substrate-runtime-proposal-hash/Cargo.toml:sp-core = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/substrate-runtime-proposal-hash/Cargo.toml:sp-io = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/substrate-runtime-proposal-hash/Cargo.toml:sp-runtime = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/substrate-runtime-proposal-hash/Cargo.toml:sp-wasm-interface = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-loader/Cargo.toml:sp-maybe-compressed-blob = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate/" }
libs/wasm-testbed/Cargo.toml:sc-executor = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sc-executor-common = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-core = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-io = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-runtime = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-state-machine = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-wasm-interface = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
libs/wasm-testbed/Cargo.toml:sp-version = { tag = "monthly-2022-07", git = "https://github.com/paritytech/substrate" }
```

### CODE REVIEW

**Comment by chevdor** [comment]
@btwiuse Thank you very much for contacting me and handing those back to me 🤗 

Regarding your comment above, I indeed recently moved back to using the substrate monthly to keep subwasm fairly up to date. I will check what can be done.

I would also appreciate if you could provide ownership on the following packages:
- [sp-maybe-compressed-blob](https://crates.io/crates/sp-maybe-compressed-blob)
- subkey [subkey = "2.0.1"](https://crates.io/crates/subkey)
- [subsee](https://crates.io/crates/subsee)

I work for Parity so you can actually send me all the Paritytech related crates and I can redispatch them.
Most will go back to https://crates.io/users/parity-crate-owner

**Comment by chevdor** [comment]
I found one more: https://crates.io/crates/sc-allocator

**Comment by btwiuse** [comment]
I have invited you as owner of the crates mentioned above.

**Comment by chevdor** [comment]
Thank you very much @btwiuse ❤️

**Comment by chevdor** [comment]
Closing for now, it will be publishedd as soon as the deps are published and up to date.

**Pull request closed without merging**
