### PR TITLE
fix: increase memory allocation 

### PR DESCRIPTION
**Pull request by Slesarew**
to actually read modern kusama and polkadot wasm

### CODE REVIEW

**Comment by chevdor** [comment]
Why not but I am doubting this is necessary as I can load the current WASM totally fine.
Your change would allows a 1GB runtime ?

**Comment by Slesarew** [comment]
I was generating metadata from https://github.com/paritytech/polkadot/releases/tag/v0.9.15 and both Kusama and Polkadot failed on the call, not on the loading. I had to modify the size to do just this:

```

    let testbed = WasmTestBed::new(&Source::File(PathBuf::from("kusama_runtime-v9150.compact.compressed.wasm"))).unwrap();
    let meta = testbed.metadata();
    let meta_vec = [vec![109, 101, 116, 97], meta.encode()].concat();
    
    let out = [meta_vec.encode(), hex::decode("b0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe").unwrap()].concat();
    
    std::fs::write("sign_me_load_metadata_kusamaV9150", &out).unwrap();
```

As of exact size bump, I've multiplied it by 10 just because if we hit limits arbitrarily, we need 1 order of magnitude to not see this again in a month, and then just rounded it to something reasonable. Is 1GB a problem? Maybe we can make a low-memory limit cargo feature (and I suppose high memory-limit should be a default if it is needed for Polkadot?).

Honestly, I should've added a test for this as well, to fetch latest tagged release of the *networks-that-have-to-be-supported-out-of-the-box* and just do things to them in CI. Maybe later.

**Comment by chevdor** [comment]
The thing is that I already mutliplied by x10 :)
The runtime should be around 5MB. This is why the current limit is set at 50MB.
I would like to understand this issue better before merging.

**Comment by chevdor** [comment]
Could you test with the current master and confirm that this is working now?
CI picked up a similar issue sporadically and I think I got a proper fix for it.

**Comment by varovainen** [comment]
Checked. It now works indeed.
Signer was switched to use `sc-executor` though, and there is no dependency on this crate anymore.

**Comment by chevdor** [comment]
Closing as the issue is now fixed without requiring a huge bump of memory allocation.

**Pull request closed without merging**
