### PR TITLE
authorize call hash

### PR DESCRIPTION
**Pull request by chevdor**
Fixes on top of #89

### CODE REVIEW

**Comment by ntn-x2** [comment]
Hello! When can we expect a released version that contains this fix?

**Comment by ntn-x2** [comment]
@chevdor

**Comment by chevdor** [comment]
I will publish a new version at some point yes, as soon as I find a little time to do so :)

**Comment by ntn-x2** [comment]
@chevdor can I assist you in any way to make your life easier?

**Comment by chevdor** [comment]
Very kind of you. Thanks for your patience. See https://github.com/chevdor/subwasm/releases/tag/v0.21.0

**Comment by ntn-x2** [comment]
Thank you @chevdor, very lovely ♥️! What about an srtool release that includes it?

**Comment by chevdor** [comment]
There may be a new path release before that. See #92

**Comment by ntn-x2** [comment]
Hey @chevdor, I can see that subwasm 0.21.2 was released. Is anything else blocking the release of a new srtool version?

**Pull request merged**
